ada:
  Port: 8088
  Code: 1013
  IP: http://123.57.67.197
  TOKEN: csh
  APPID: wxa8786bf0a6c71871
  APPSECRET: f51bc399be4e020b231bacbb4dcaa53f
spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ada?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password:
mybatis:
  mapper-locations: classpath:/mapper/**.xml
path:
  log: /usr/local/log