package com.csh.ada.pojo;

import java.util.Date;

public class AdaBC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.adaId
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private String adaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.adaCode
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private Integer adacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.adaUid
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private String adauid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.adaToken
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private String adatoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.adaName
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private String adaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.adaIP
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private String adaip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.adaPort
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private String adaport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.createTime
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ada.updateTime
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.adaId
     *
     * @return the value of ada.adaId
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public String getAdaid() {
        return adaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.adaId
     *
     * @param adaid the value for ada.adaId
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setAdaid(String adaid) {
        this.adaid = adaid == null ? null : adaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.adaCode
     *
     * @return the value of ada.adaCode
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public Integer getAdacode() {
        return adacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.adaCode
     *
     * @param adacode the value for ada.adaCode
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setAdacode(Integer adacode) {
        this.adacode = adacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.adaUid
     *
     * @return the value of ada.adaUid
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public String getAdauid() {
        return adauid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.adaUid
     *
     * @param adauid the value for ada.adaUid
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setAdauid(String adauid) {
        this.adauid = adauid == null ? null : adauid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.adaToken
     *
     * @return the value of ada.adaToken
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public String getAdatoken() {
        return adatoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.adaToken
     *
     * @param adatoken the value for ada.adaToken
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setAdatoken(String adatoken) {
        this.adatoken = adatoken == null ? null : adatoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.adaName
     *
     * @return the value of ada.adaName
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public String getAdaname() {
        return adaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.adaName
     *
     * @param adaname the value for ada.adaName
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setAdaname(String adaname) {
        this.adaname = adaname == null ? null : adaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.adaIP
     *
     * @return the value of ada.adaIP
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public String getAdaip() {
        return adaip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.adaIP
     *
     * @param adaip the value for ada.adaIP
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setAdaip(String adaip) {
        this.adaip = adaip == null ? null : adaip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.adaPort
     *
     * @return the value of ada.adaPort
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public String getAdaport() {
        return adaport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.adaPort
     *
     * @param adaport the value for ada.adaPort
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setAdaport(String adaport) {
        this.adaport = adaport == null ? null : adaport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.createTime
     *
     * @return the value of ada.createTime
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.createTime
     *
     * @param createtime the value for ada.createTime
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ada.updateTime
     *
     * @return the value of ada.updateTime
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ada.updateTime
     *
     * @param updatetime the value for ada.updateTime
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}