package com.csh.ada.dao;

import com.csh.ada.pojo.AdaBC;
import com.csh.ada.pojo.AdaBCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdaBCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int countByExample(AdaBCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int deleteByExample(AdaBCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int deleteByPrimaryKey(String adaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int insert(AdaBC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int insertSelective(AdaBC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    List<AdaBC> selectByExample(AdaBCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    AdaBC selectByPrimaryKey(String adaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdaBC record, @Param("example") AdaBCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int updateByExample(@Param("record") AdaBC record, @Param("example") AdaBCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int updateByPrimaryKeySelective(AdaBC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ada
     *
     * @mbggenerated Sun Dec 23 23:12:10 CST 2018
     */
    int updateByPrimaryKey(AdaBC record);
}